### ISSUE TITLE
non-users entries allowed

### ISSUE THREAD

**Issue by ahmednoureldeen** [cartologic/cartoview_workforce_manager#11]
verify that entries are existing users

![image](https://user-images.githubusercontent.com/10349762/30378921-19f9d6a4-9895-11e7-8ba0-5318f3ad8146.png)

**Comment by Amira-Mohiey** [comment]
fixed

**Comment by ahmednoureldeen** [comment]
don't close issues just move it done pipeline

**Comment by ahmednoureldeen** [comment]
have the same issue
